import React, { useMemo, useState } from 'react';
const features = ["Opportunity Qualification","Compliance Matrix Builder","Proposal Volume Planner","Past Performance Matcher","Teaming Partner Tracker","Pricing Strategy Board","Subcontractor Flowdowns","SAM/UEI Readiness","Certifications Tracker","Q&A Amendment Monitor","Color Team Review","Submission Checklist","Win Theme Builder","Contract Award Handoff","Debrief Analysis"];
const statuses = ['Open','Review','Queued','Approval pending','Urgent','Exception','Completed'];
const priorities = ['High','Medium','Low','Urgent'];
function recordsFor(feature) { return Array.from({ length: 15 }, (_, index) => ({ id: feature.toLowerCase().replace(/[^a-z0-9]+/g, '-') + '-' + (index + 1), name: feature + ' ' + ['intake review','policy validation','evidence check','missing documentation request','approval routing','connector follow-up','SLA escalation','risk exception review','stakeholder update task','readiness check','credential or source blocker','audit evidence packet','financial impact review','manager signoff','completed sample'][index], status: statuses[index % statuses.length], owner: index % 5 === 0 ? 'Operations Lead' : index % 3 === 0 ? 'Specialist Reviewer' : 'Operations Analyst', dueDate: '2026-06-' + String(7 + index).padStart(2, '0'), priority: priorities[index % priorities.length] })); }
function ReadinessRows() { return Array.from({ length: 15 }, (_, index) => ({ id: 'ready-' + (index + 1), name: ['Enterprise identity access','Connector operations center','Audit export center','Notification delivery ledger','Observability runbook','Release test harness','Production gap workspace','Credential readiness','Role mapping','Webhook retry queue','Data retention control','Evidence packet export','Browser smoke check','API health check','Launch approval gate'][index], status: index % 7 === 0 ? 'Blocked' : index % 5 === 0 ? 'Needs setup' : index % 3 === 0 ? 'Queued' : 'Done', owner: index % 4 === 0 ? 'Platform Lead' : 'Operations Lead', evidence: 'Government Contracts readiness evidence ' + (index + 1), nextAction: index % 7 === 0 ? 'Add credentials or approval owner' : 'Keep evidence current and monitor exceptions' })); }
const card = { background: '#fff', border: '1px solid #d8dee8', borderRadius: 8, padding: 16, boxShadow: '0 1px 2px rgba(15,23,42,.06)' };
const th = { textAlign: 'left', padding: 10, background: '#f8fafc', borderBottom: '1px solid #e2e8f0' };
const td = { padding: 10, borderBottom: '1px solid #edf2f7', verticalAlign: 'top' };
export default function MissingFeaturesHub() {
 const [selected, setSelected] = useState(features[0]); const rows = useMemo(() => recordsFor(selected), [selected]);
 return <div style={{ padding: 24, background: '#f6f8fb', minHeight: '100vh' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 16, alignItems: 'flex-start', marginBottom: 18 }}><div><div style={{ color: '#475569', fontSize: 12, textTransform: 'uppercase', letterSpacing: 1 }}>Missing Features</div><h1 style={{ margin: '4px 0', color: '#0f172a' }}>Missing Features Hub</h1><p style={{ margin: 0, color: '#475569' }}>Prior-authorization-style workspace for Government Contracts: subfeatures, queues, owners, controls, evidence, and audit-ready records.</p></div><div style={{ ...card, minWidth: 180 }}><strong>{rows.length}</strong><div style={{ color: '#64748b' }}>items shown</div></div></div>{true && <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 10, marginBottom: 18 }}>{features.map((feature) => <button key={feature} onClick={() => setSelected(feature)} style={{ ...card, textAlign: 'left', cursor: 'pointer', borderColor: selected === feature ? '#2563eb' : '#d8dee8' }}><strong>{feature}</strong><div style={{ color: '#64748b', marginTop: 6 }}>15 records with work queue, controls, and audit evidence</div></button>)}</div>}<div style={card}><h2 style={{ marginTop: 0 }}>{selected}</h2><div style={{ overflowX: 'auto' }}><table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14 }}><thead><tr><th style={th}>Name</th><th style={th}>Status</th><th style={th}>Owner</th><th style={th}>Due / Evidence</th><th style={th}>Priority / Next Action</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td style={td}>{row.name}</td><td style={td}>{row.status}</td><td style={td}>{row.owner}</td><td style={td}>{row.dueDate || row.evidence}</td><td style={td}>{row.priority || row.nextAction}</td></tr>)}</tbody></table></div></div></div>;
}
